# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainPageWindow(object):
    def setupUi(self, MainPageWindow):
        MainPageWindow.setObjectName("MainPageWindow")
        MainPageWindow.resize(882, 494)
        MainPageWindow.setMouseTracking(True)
        MainPageWindow.setStyleSheet("QWidget#widget_3,\n"
"QWidget#page,\n"
"QWidget#page_2,\n"
"QWidget#page_3,\n"
"QWidget#page_4{\n"
"\n"
"   background-color: qlineargradient(spread:pad, x1:0.199, y1:0.244318, x2:1, y2:1, stop:0 rgba(66, 2, 157), stop:1 rgba(rgb(4,7,47)));\n"
"  }\n"
"\n"
"QScrollBar:vertical {\n"
"\n"
"    background: #FFFFFF;  /* Белый цвет фона */\n"
"    width: 12px;\n"
"    margin: 0px;\n"
"    border-radius: 5px;\n"
"  }\n"
"\n"
"QScrollBar::handle:vertical {\n"
"\n"
"    background: #6900FF;  /* Фиолетовый цвет слайдера */\n"
"    border-radius: 5px;\n"
"    border: 2px solid #000000;\n"
"       /* Закругление углов слайдера */\n"
"\n"
"  }\n"
"\n"
"QScrollBar::add-page, QScrollBar::sub-page {\n"
"\n"
"    background: none;\n"
"  }\n"
"\n"
"QScrollBar::add-line, QScrollBar::sub-line {\n"
"\n"
"    border: none;\n"
"    background: none;\n"
"}\n"
"\n"
"/*Выпадающего списка*/\n"
"QComboBox QAbstractItemView {\n"
"\n"
"        background-color: #FFFFFF;  \n"
"        border-bottom-left-radius: 10px;\n"
"        border-top-right-radius: 10px;\n"
"    }\n"
"\n"
"QComboBox::drop-down {\n"
"\n"
"        border-left-color: #fffffff;\n"
"        border-left-style: solid;\n"
"        border-top-right-radius: 10px; \n"
"        border-bottom-right-radius: 10px; \n"
"        background-color: #fffffff;\n"
"        padding-right: 10px;\n"
"    }\n"
"\n"
" QComboBox::down-arrow {\n"
"\n"
"        image: url(:/icons/icon/chevron-down.svg);\n"
"    }\n"
"\n"
"QComboBox::down-arrow:on {\n"
"\n"
"    image: url(:/icons/icon/up.svg);\n"
"    }\n"
"\n"
"\n"
"\n"
"/*Выпадающего списка*/\n"
"QCalendarWidget QMenu{\n"
"\n"
"    background-color:rgba(105, 0, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 8pt \"Arial\";\n"
"}\n"
"\n"
"#qt_calendar_calendarview {\n"
"\n"
"    background-color: #AA80E4;\n"
"    font: 87 10pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"    alternate-background-color:rgba(105, 0, 255, 0.6);\n"
"    \n"
"}\n"
"\n"
"#qt_calendar_monthbutton {\n"
"\n"
"    width: 70px;\n"
"    background-color: rgba(105, 0, 255 ,0);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"#qt_calendar_yearbutton {\n"
"  \n"
"    background-color: rgba(105, 0, 255 ,0);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"#qt_calendar_yearedit {\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"#qt_calendar_navigationbar {\n"
"\n"
"    border-top-right-radius: 20px;\n"
"    border-top-left-radius: 20px; \n"
"    background-color: rgba(105, 0, 255 ,0.9);\n"
"}\n"
"\n"
"QToolButton#qt_calendar_prevmonth {\n"
"    background: transparent;\n"
"    border: none;\n"
"    width: 40px;\n"
"    qproperty-icon: url(:/icons/icon/Vector.svg);\n"
"}\n"
"\n"
"QToolButton#qt_calendar_nextmonth {\n"
"    background: transparent;\n"
"    border: none;\n"
"    width: 40px;\n"
"    qproperty-icon: url(:/icons/icon/leftsvg.svg);\n"
"}\n"
"\n"
"QCalendarWidget#calendarWidget {\n"
"    background-color:transperent;\n"
"}\n"
"\n"
"QCalendarWidget QTableView {\n"
"        selection-background-color: white;  /* Цвет фона выделенной ячейки */\n"
"        alternate-background-color: white;\n"
"        selection-color: rgba(66, 2, 157, 1);\n"
"        selection-border-radius: 5px;\n"
" /* Цвет фона чередующихся ячеек */\n"
"    }\n"
"\n"
"QCalendarWidget QSpinBox::up-button{\n"
"    image: url(:/icons/icon/up.svg);width:15px;\n"
"}\n"
"\n"
"QCalendarWidget QSpinBox::down-button{\n"
"    image: url(:/icons/icon/down.svg);width:15px;\n"
"}\n"
"\n"
"QCheckBox {\n"
"    spacing: 5px; /* Расстояние между значком и текстом */\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 10px; /* Ширина значка */\n"
"    height: 10px; /* Высота значка */\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    border: 1px solid rgb(66, 2, 157); /* Граница для невыбранного состояния */\n"
"    background-color: white; /* Фоновый цвет для невыбранного состояния */\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    border: 1px solid rgb(66, 2, 157); /* Граница для выбранного состояния */\n"
"    background-color: #3FE103; /* Фоновый цвет для выбранного состояния */\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:hover,\n"
"QCheckBox::indicator:checked:hover {\n"
"    border: 2px solid rgb(105, 0, 255); /* Граница при наведении курсора */\n"
"}\n"
"\n"
" QComboBox {\n"
"        background-color: #FFFFFF;  /* Белый цвет фона комбобокса */\n"
"        border-radius: 10px;  /* Закругление углов комбобокса */\n"
"        padding-left: 35px;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 1px solid rgb(105, 0, 255);\n"
"}\n"
"\n"
" QComboBox QAbstractItemView {\n"
"        background-color: #FFFFFF;  /* Белый цвет фона выпадающего списка */\n"
"        border-radius: 10px;  /* Закругление углов выпадающего списка */\n"
"    }\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        MainPageWindow.setAnimated(True)
        MainPageWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainPageWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("#left_menu\n"
"{\n"
"    background-color: rgb(43, 25, 68);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#main_Menu \n"
"{\n"
"    background-color: rgb(43, 25, 68);\n"
"}\n"
"\n"
"#buttonMenu,\n"
"#button_left_Home,\n"
"#button_leftCalendar,\n"
"#button_left_Notes,\n"
"#button_left_Settings,\n"
"#buttonBack\n"
"{\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"#buttonHome\n"
"{\n"
"     padding:4px;\n"
"     text-align: left;\n"
"     border-top-left-radius: 0px;\n"
"}\n"
"#buttonCalendar \n"
"{\n"
"     padding:4px;\n"
"     text-align: left;\n"
"     border-top-left-radius: 0px;\n"
"}\n"
"\n"
"#buttonNotes \n"
"{\n"
"     padding:6px;\n"
"     text-align: left;\n"
"     border-top-left-radius: 0px;\n"
"}\n"
"\n"
"#buttonSettings\n"
"{\n"
"     padding:6px;\n"
"     text-align: left;\n"
"     border-top-left-radius: 0px;\n"
"}\n"
"#scrollArea\n"
" {\n"
"    background-color: rgba(217, 217, 217, 0.40);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"#scrollArea_2\n"
" {\n"
"    background-color: rgba(217, 217, 217, 0.40);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"#scrollAreaWidgetContents \n"
"{\n"
"    background-color: transparent;  /* Прозрачный фон */\n"
"}\n"
"\n"
"#scrollAreaWidgetContents_2\n"
"{\n"
"    background-color: transparent;  /* Прозрачный фон */\n"
"}\n"
"\n"
"#button_theme_1,\n"
"#button_theme_2,\n"
"#button_theme_3\n"
"{\n"
"    border-radius: 20px;\n"
"    border: 2px solid #D2FA00;\n"
"}\n"
"\n"
"#button_theme_1\n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:0.199, y1:0.244318, x2:1, y2:1, stop:0 rgba(66, 2, 157), stop:1 rgba(rgb(4,7,47)));\n"
"}\n"
"\n"
"#button_theme_2\n"
"{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"#button_theme_3\n"
"{\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"#button_update,\n"
"#button_notifications\n"
"{\n"
"    color: rgb(66, 2, 157);\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.3);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"\n"
"    \n"
"\n"
"\n"
"\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.left_menu = QtWidgets.QWidget(self.centralwidget)
        self.left_menu.setMinimumSize(QtCore.QSize(50, 0))
        self.left_menu.setMaximumSize(QtCore.QSize(50, 16777215))
        self.left_menu.setStyleSheet("")
        self.left_menu.setObjectName("left_menu")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.left_menu)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setHorizontalSpacing(0)
        self.gridLayout_3.setVerticalSpacing(8)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.button_left_Notes = QtWidgets.QPushButton(self.left_menu)
        self.button_left_Notes.setMaximumSize(QtCore.QSize(28, 28))
        self.button_left_Notes.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_left_Notes.setStyleSheet("")
        self.button_left_Notes.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icon/note.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_left_Notes.setIcon(icon)
        self.button_left_Notes.setIconSize(QtCore.QSize(26, 26))
        self.button_left_Notes.setCheckable(True)
        self.button_left_Notes.setObjectName("button_left_Notes")
        self.gridLayout_3.addWidget(self.button_left_Notes, 3, 0, 1, 1)
        self.button_left_Home = QtWidgets.QPushButton(self.left_menu)
        self.button_left_Home.setMaximumSize(QtCore.QSize(28, 28))
        self.button_left_Home.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_left_Home.setStyleSheet("")
        self.button_left_Home.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icon/home.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_left_Home.setIcon(icon1)
        self.button_left_Home.setIconSize(QtCore.QSize(26, 26))
        self.button_left_Home.setCheckable(True)
        self.button_left_Home.setObjectName("button_left_Home")
        self.gridLayout_3.addWidget(self.button_left_Home, 1, 0, 1, 1)
        self.button_left_Settings = QtWidgets.QPushButton(self.left_menu)
        self.button_left_Settings.setMaximumSize(QtCore.QSize(28, 28))
        self.button_left_Settings.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_left_Settings.setStyleSheet("")
        self.button_left_Settings.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icon/settings.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_left_Settings.setIcon(icon2)
        self.button_left_Settings.setIconSize(QtCore.QSize(24, 24))
        self.button_left_Settings.setCheckable(True)
        self.button_left_Settings.setObjectName("button_left_Settings")
        self.gridLayout_3.addWidget(self.button_left_Settings, 4, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 220, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem, 5, 0, 1, 1)
        self.button_leftCalendar = QtWidgets.QPushButton(self.left_menu)
        self.button_leftCalendar.setMaximumSize(QtCore.QSize(28, 28))
        self.button_leftCalendar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_leftCalendar.setStyleSheet("")
        self.button_leftCalendar.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icon/calendar (1).svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_leftCalendar.setIcon(icon3)
        self.button_leftCalendar.setIconSize(QtCore.QSize(26, 26))
        self.button_leftCalendar.setCheckable(True)
        self.button_leftCalendar.setObjectName("button_leftCalendar")
        self.gridLayout_3.addWidget(self.button_leftCalendar, 2, 0, 1, 1)
        self.buttonMenu = QtWidgets.QPushButton(self.left_menu)
        self.buttonMenu.setMaximumSize(QtCore.QSize(28, 28))
        self.buttonMenu.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonMenu.setStyleSheet("")
        self.buttonMenu.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icon/menu.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonMenu.setIcon(icon4)
        self.buttonMenu.setIconSize(QtCore.QSize(26, 26))
        self.buttonMenu.setCheckable(True)
        self.buttonMenu.setObjectName("buttonMenu")
        self.gridLayout_3.addWidget(self.buttonMenu, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.left_menu, 0, 0, 1, 1)
        self.main_Menu = QtWidgets.QWidget(self.centralwidget)
        self.main_Menu.setMinimumSize(QtCore.QSize(140, 0))
        self.main_Menu.setMaximumSize(QtCore.QSize(140, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.main_Menu.setFont(font)
        self.main_Menu.setStyleSheet("")
        self.main_Menu.setObjectName("main_Menu")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.main_Menu)
        self.gridLayout_2.setContentsMargins(0, 4, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(0)
        self.gridLayout_2.setVerticalSpacing(18)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.buttonCalendar = QtWidgets.QPushButton(self.main_Menu)
        self.buttonCalendar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonCalendar.setStyleSheet("font: 87 10pt \"Arial\";\n"
"color: rgb(255, 255, 255);")
        self.buttonCalendar.setIcon(icon3)
        self.buttonCalendar.setIconSize(QtCore.QSize(26, 26))
        self.buttonCalendar.setCheckable(True)
        self.buttonCalendar.setObjectName("buttonCalendar")
        self.gridLayout_2.addWidget(self.buttonCalendar, 2, 0, 1, 2)
        self.buttonHome = QtWidgets.QPushButton(self.main_Menu)
        self.buttonHome.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonHome.setStyleSheet("font: 87 10pt \"Arial\";\n"
"color: rgb(255, 255, 255);color: rgb(255, 255, 255);")
        self.buttonHome.setIcon(icon1)
        self.buttonHome.setIconSize(QtCore.QSize(26, 26))
        self.buttonHome.setCheckable(True)
        self.buttonHome.setObjectName("buttonHome")
        self.gridLayout_2.addWidget(self.buttonHome, 1, 0, 1, 2)
        self.buttonBack = QtWidgets.QPushButton(self.main_Menu)
        self.buttonBack.setMinimumSize(QtCore.QSize(25, 25))
        self.buttonBack.setMaximumSize(QtCore.QSize(25, 25))
        self.buttonBack.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonBack.setStyleSheet("")
        self.buttonBack.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icon/Vector.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonBack.setIcon(icon5)
        self.buttonBack.setCheckable(True)
        self.buttonBack.setObjectName("buttonBack")
        self.gridLayout_2.addWidget(self.buttonBack, 0, 1, 1, 1)
        self.buttonSettings = QtWidgets.QPushButton(self.main_Menu)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.buttonSettings.setFont(font)
        self.buttonSettings.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonSettings.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 87 10pt \"Arial\";\n"
"\n"
"")
        self.buttonSettings.setIcon(icon2)
        self.buttonSettings.setIconSize(QtCore.QSize(24, 24))
        self.buttonSettings.setCheckable(True)
        self.buttonSettings.setObjectName("buttonSettings")
        self.gridLayout_2.addWidget(self.buttonSettings, 4, 0, 1, 2)
        self.buttonNotes = QtWidgets.QPushButton(self.main_Menu)
        self.buttonNotes.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonNotes.setStyleSheet("font: 87 10pt \"Arial\";\n"
"color: rgb(255, 255, 255);")
        self.buttonNotes.setIcon(icon)
        self.buttonNotes.setIconSize(QtCore.QSize(24, 24))
        self.buttonNotes.setCheckable(True)
        self.buttonNotes.setObjectName("buttonNotes")
        self.gridLayout_2.addWidget(self.buttonNotes, 3, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 140, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem1, 5, 0, 1, 1)
        self.logoLabel = QtWidgets.QLabel(self.main_Menu)
        self.logoLabel.setText("")
        self.logoLabel.setPixmap(QtGui.QPixmap(":/image/images/logo_panel.png"))
        self.logoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.logoLabel.setObjectName("logoLabel")
        self.gridLayout_2.addWidget(self.logoLabel, 6, 0, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 35, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem2, 0, 0, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 7)
        self.gridLayout.addWidget(self.main_Menu, 0, 1, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setStyleSheet("")
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.widget_4 = QtWidgets.QWidget(self.widget_3)
        self.widget_4.setStyleSheet("    background-color: transparent;")
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_5.setContentsMargins(0, 5, 10, 0)
        self.gridLayout_5.setHorizontalSpacing(10)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButton_12 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_12.setMaximumSize(QtCore.QSize(16, 16))
        self.pushButton_12.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_12.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icon/minus-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_12.setIcon(icon6)
        self.pushButton_12.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_5.addWidget(self.pushButton_12, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(595, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem3, 0, 0, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_11.setMaximumSize(QtCore.QSize(16, 16))
        self.pushButton_11.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_11.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icon/x-circle 1.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_11.setIcon(icon7)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_5.addWidget(self.pushButton_11, 0, 2, 1, 1)
        self.gridLayout_4.addWidget(self.widget_4, 0, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget_3)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setStyleSheet("")
        self.page.setObjectName("page")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setSpacing(0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.widget = QtWidgets.QWidget(self.page)
        self.widget.setMinimumSize(QtCore.QSize(170, 155))
        self.widget.setMaximumSize(QtCore.QSize(170, 155))
        self.widget.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255,255,255,.40);\n"
"border-radius: 20px;")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: transparent;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: transparent;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.gridLayout_10.addWidget(self.widget, 1, 4, 3, 3)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem6, 4, 7, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_10.addItem(spacerItem7, 0, 5, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem8, 2, 7, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem9, 3, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_10.addItem(spacerItem10, 4, 5, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_10.addWidget(self.label_16, 6, 4, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.page)
        self.label_15.setMaximumSize(QtCore.QSize(175, 160))
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap(":/image/images/aquarium.png"))
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.gridLayout_10.addWidget(self.label_15, 5, 3, 1, 3)
        spacerItem11 = QtWidgets.QSpacerItem(68, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem11, 4, 2, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.page)
        self.scrollArea.setMinimumSize(QtCore.QSize(350, 25))
        self.scrollArea.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollArea.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 338, 390))
        self.scrollAreaWidgetContents.setStyleSheet("")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.widget_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_2.setMinimumSize(QtCore.QSize(300, 120))
        self.widget_2.setMaximumSize(QtCore.QSize(250, 120))
        self.widget_2.setStyleSheet("background-color: rgba(255,255,255,.70);\n"
"color: rgb(66, 2, 157);\n"
"border-radius: 20px;")
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem12 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem12, 0, 7, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget_2)
        self.label_6.setStyleSheet("background-color: transparent;")
        self.label_6.setObjectName("label_6")
        self.gridLayout_6.addWidget(self.label_6, 2, 1, 1, 4)
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(105, 0, 255);\n"
"background-color: transparent;")
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 0, 2, 1, 2)
        spacerItem13 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem13, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.widget_2)
        self.line.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line.setStyleSheet("background-color: rgb(66, 2, 157);")
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setLineWidth(1)
        self.line.setMidLineWidth(0)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.gridLayout_6.addWidget(self.line, 1, 0, 1, 8)
        spacerItem14 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem14, 3, 7, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setMinimumSize(QtCore.QSize(0, 20))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: transparent;")
        self.label_3.setObjectName("label_3")
        self.gridLayout_6.addWidget(self.label_3, 0, 1, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_13.setMinimumSize(QtCore.QSize(16, 16))
        self.pushButton_13.setMaximumSize(QtCore.QSize(16, 16))
        self.pushButton_13.setStyleSheet("background-color: transparent;")
        self.pushButton_13.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/static/icon/trash-2.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_13.setIcon(icon8)
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout_6.addWidget(self.pushButton_13, 0, 6, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setMinimumSize(QtCore.QSize(0, 20))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: transparent;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 0, 5, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox_3.setStyleSheet("background-color: transparent;")
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_6.addWidget(self.checkBox_3, 3, 5, 1, 1)
        self.gridLayout_9.addWidget(self.widget_2, 0, 0, 1, 1)
        self.widget_5 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_5.setMinimumSize(QtCore.QSize(300, 120))
        self.widget_5.setMaximumSize(QtCore.QSize(250, 120))
        self.widget_5.setStyleSheet("background-color: rgba(255,255,255,.70);\n"
"color: rgb(66, 2, 157);\n"
"border-radius: 20px;")
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.checkBox_2 = QtWidgets.QCheckBox(self.widget_5)
        self.checkBox_2.setStyleSheet("background-color: transparent;")
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_7.addWidget(self.checkBox_2, 3, 6, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widget_5)
        self.label_9.setMinimumSize(QtCore.QSize(0, 20))
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color: transparent;")
        self.label_9.setObjectName("label_9")
        self.gridLayout_7.addWidget(self.label_9, 0, 1, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem15, 0, 8, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget_5)
        self.label_7.setStyleSheet("background-color: transparent;")
        self.label_7.setObjectName("label_7")
        self.gridLayout_7.addWidget(self.label_7, 2, 1, 1, 4)
        self.label_8 = QtWidgets.QLabel(self.widget_5)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(105, 0, 255);\n"
"background-color: transparent;")
        self.label_8.setObjectName("label_8")
        self.gridLayout_7.addWidget(self.label_8, 0, 2, 1, 2)
        spacerItem16 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem16, 0, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.widget_5)
        self.line_2.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line_2.setStyleSheet("background-color: rgb(66, 2, 157);")
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setLineWidth(1)
        self.line_2.setMidLineWidth(0)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.gridLayout_7.addWidget(self.line_2, 1, 0, 1, 9)
        spacerItem17 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem17, 3, 8, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.widget_5)
        self.pushButton_14.setMinimumSize(QtCore.QSize(16, 16))
        self.pushButton_14.setMaximumSize(QtCore.QSize(16, 16))
        self.pushButton_14.setStyleSheet("background-color: transparent;")
        self.pushButton_14.setText("")
        self.pushButton_14.setIcon(icon8)
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout_7.addWidget(self.pushButton_14, 0, 7, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.widget_5)
        self.label_10.setMinimumSize(QtCore.QSize(0, 20))
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color: transparent;")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_7.addWidget(self.label_10, 0, 6, 1, 1)
        self.gridLayout_9.addWidget(self.widget_5, 1, 0, 1, 1)
        self.widget_6 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_6.setMinimumSize(QtCore.QSize(300, 120))
        self.widget_6.setMaximumSize(QtCore.QSize(250, 120))
        self.widget_6.setStyleSheet("background-color: rgba(255,255,255,.70);\n"
"color: rgb(66, 2, 157);\n"
"border-radius: 20px;")
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.widget_6)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        spacerItem18 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem18, 0, 8, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.widget_6)
        self.label_11.setStyleSheet("background-color: transparent;")
        self.label_11.setObjectName("label_11")
        self.gridLayout_8.addWidget(self.label_11, 2, 1, 1, 4)
        self.label_12 = QtWidgets.QLabel(self.widget_6)
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(105, 0, 255);\n"
"background-color: transparent;")
        self.label_12.setObjectName("label_12")
        self.gridLayout_8.addWidget(self.label_12, 0, 2, 1, 2)
        spacerItem19 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem19, 0, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.widget_6)
        self.label_13.setMinimumSize(QtCore.QSize(0, 20))
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("background-color: transparent;")
        self.label_13.setObjectName("label_13")
        self.gridLayout_8.addWidget(self.label_13, 0, 1, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.widget_6)
        self.line_3.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line_3.setStyleSheet("background-color: rgb(66, 2, 157);")
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setLineWidth(1)
        self.line_3.setMidLineWidth(0)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setObjectName("line_3")
        self.gridLayout_8.addWidget(self.line_3, 1, 0, 1, 9)
        spacerItem20 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem20, 3, 8, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.widget_6)
        self.pushButton_15.setMinimumSize(QtCore.QSize(16, 16))
        self.pushButton_15.setMaximumSize(QtCore.QSize(16, 16))
        self.pushButton_15.setStyleSheet("background-color: transparent;")
        self.pushButton_15.setText("")
        self.pushButton_15.setIcon(icon8)
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout_8.addWidget(self.pushButton_15, 0, 7, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.widget_6)
        self.label_14.setMinimumSize(QtCore.QSize(0, 20))
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("background-color: transparent;")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_8.addWidget(self.label_14, 0, 6, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.widget_6)
        self.checkBox.setStyleSheet("background-color: transparent;")
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_8.addWidget(self.checkBox, 3, 6, 1, 1)
        self.gridLayout_9.addWidget(self.widget_6, 2, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_10.addWidget(self.scrollArea, 1, 1, 5, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setStyleSheet("")
        self.page_2.setObjectName("page_2")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.widget_14 = QtWidgets.QWidget(self.page_2)
        self.widget_14.setMinimumSize(QtCore.QSize(600, 400))
        self.widget_14.setMaximumSize(QtCore.QSize(600, 500))
        self.widget_14.setObjectName("widget_14")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_14)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.widget_14)
        self.calendarWidget.setMinimumSize(QtCore.QSize(580, 370))
        self.calendarWidget.setMaximumSize(QtCore.QSize(580, 370))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.calendarWidget.setFont(font)
        self.calendarWidget.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.calendarWidget.setStyleSheet("")
        self.calendarWidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.calendarWidget.setFirstDayOfWeek(QtCore.Qt.Monday)
        self.calendarWidget.setGridVisible(False)
        self.calendarWidget.setSelectionMode(QtWidgets.QCalendarWidget.SingleSelection)
        self.calendarWidget.setHorizontalHeaderFormat(QtWidgets.QCalendarWidget.ShortDayNames)
        self.calendarWidget.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.calendarWidget.setNavigationBarVisible(True)
        self.calendarWidget.setDateEditEnabled(False)
        self.calendarWidget.setObjectName("calendarWidget")
        self.verticalLayout_3.addWidget(self.calendarWidget)
        self.label_42 = QtWidgets.QLabel(self.widget_14)
        self.label_42.setMinimumSize(QtCore.QSize(580, 20))
        self.label_42.setMaximumSize(QtCore.QSize(580, 20))
        self.label_42.setStyleSheet("background-color: #AA80E4;\n"
"border-bottom-left-radius:20px;\n"
"border-bottom-right-radius:20px;")
        self.label_42.setText("")
        self.label_42.setObjectName("label_42")
        self.verticalLayout_3.addWidget(self.label_42)
        spacerItem21 = QtWidgets.QSpacerItem(4, 14, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem21)
        self.gridLayout_21.addWidget(self.widget_14, 1, 2, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_21.addItem(spacerItem22, 1, 0, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_21.addItem(spacerItem23, 1, 3, 1, 1)
        spacerItem24 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_21.addItem(spacerItem24, 0, 2, 1, 1)
        spacerItem25 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_21.addItem(spacerItem25, 2, 3, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setStyleSheet("QPushButton:hover {\n"
"    border: 2px solid rgb(105, 0, 255);\n"
"}\n"
"")
        self.page_3.setObjectName("page_3")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_14.setObjectName("gridLayout_14")
        spacerItem26 = QtWidgets.QSpacerItem(20, 16, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_14.addItem(spacerItem26, 0, 1, 1, 1)
        spacerItem27 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem27, 1, 0, 1, 1)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.page_3)
        self.scrollArea_2.setMinimumSize(QtCore.QSize(600, 400))
        self.scrollArea_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollArea_2.setStyleSheet("")
        self.scrollArea_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 588, 400))
        self.scrollAreaWidgetContents_2.setStyleSheet("QPushButton:hover {\n"
"    padding: 10px;\n"
"}")
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.widget_8 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_8.setMinimumSize(QtCore.QSize(250, 120))
        self.widget_8.setMaximumSize(QtCore.QSize(250, 120))
        self.widget_8.setStyleSheet("background-color: rgba(255,255,255,.70);\n"
"color: rgb(66, 2, 157);\n"
"border-radius: 20px;")
        self.widget_8.setObjectName("widget_8")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.widget_8)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setSpacing(0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_21 = QtWidgets.QLabel(self.widget_8)
        self.label_21.setMinimumSize(QtCore.QSize(0, 20))
        self.label_21.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("background-color: transparent;")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_13.addWidget(self.label_21, 0, 4, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.widget_8)
        self.label_22.setStyleSheet("background-color: transparent;")
        self.label_22.setObjectName("label_22")
        self.gridLayout_13.addWidget(self.label_22, 2, 1, 1, 4)
        spacerItem28 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem28, 0, 0, 1, 1)
        spacerItem29 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem29, 0, 5, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.widget_8)
        self.label_23.setMinimumSize(QtCore.QSize(0, 20))
        self.label_23.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("color: rgb(105, 0, 255);\n"
"background-color: transparent;")
        self.label_23.setObjectName("label_23")
        self.gridLayout_13.addWidget(self.label_23, 0, 2, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.widget_8)
        self.label_24.setMinimumSize(QtCore.QSize(0, 20))
        self.label_24.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("background-color: transparent;")
        self.label_24.setObjectName("label_24")
        self.gridLayout_13.addWidget(self.label_24, 0, 1, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.widget_8)
        self.line_5.setMinimumSize(QtCore.QSize(0, 1))
        self.line_5.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line_5.setStyleSheet("background-color: rgb(66, 2, 157);")
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setLineWidth(1)
        self.line_5.setMidLineWidth(0)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setObjectName("line_5")
        self.gridLayout_13.addWidget(self.line_5, 1, 0, 1, 6)
        self.gridLayout_11.addWidget(self.widget_8, 2, 1, 1, 1)
        self.widget_7 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_7.setMinimumSize(QtCore.QSize(250, 120))
        self.widget_7.setMaximumSize(QtCore.QSize(250, 120))
        self.widget_7.setStyleSheet("background-color: rgba(255,255,255,.70);\n"
"color: rgb(66, 2, 157);\n"
"border-radius: 20px;")
        self.widget_7.setObjectName("widget_7")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.widget_7)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setSpacing(0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        spacerItem30 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem30, 0, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.widget_7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: rgb(105, 0, 255);\n"
"background-color: transparent;")
        self.label_17.setObjectName("label_17")
        self.gridLayout_12.addWidget(self.label_17, 0, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.widget_7)
        self.label_18.setMinimumSize(QtCore.QSize(0, 20))
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("background-color: transparent;")
        self.label_18.setObjectName("label_18")
        self.gridLayout_12.addWidget(self.label_18, 0, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.widget_7)
        self.label_19.setMinimumSize(QtCore.QSize(0, 20))
        self.label_19.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("background-color: transparent;")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_12.addWidget(self.label_19, 0, 4, 1, 1)
        spacerItem31 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem31, 0, 5, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.widget_7)
        self.line_4.setMinimumSize(QtCore.QSize(0, 1))
        self.line_4.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line_4.setStyleSheet("background-color: rgb(66, 2, 157);")
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setLineWidth(1)
        self.line_4.setMidLineWidth(0)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setObjectName("line_4")
        self.gridLayout_12.addWidget(self.line_4, 1, 0, 1, 6)
        self.label_20 = QtWidgets.QLabel(self.widget_7)
        self.label_20.setStyleSheet("background-color: transparent;")
        self.label_20.setObjectName("label_20")
        self.gridLayout_12.addWidget(self.label_20, 2, 1, 1, 4)
        self.gridLayout_11.addWidget(self.widget_7, 1, 1, 1, 1)
        self.widget_10 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_10.setMinimumSize(QtCore.QSize(250, 120))
        self.widget_10.setMaximumSize(QtCore.QSize(250, 120))
        self.widget_10.setStyleSheet("background-color: rgba(255,255,255,.70);\n"
"color: rgb(66, 2, 157);\n"
"border-radius: 20px;")
        self.widget_10.setObjectName("widget_10")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.widget_10)
        self.gridLayout_15.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_15.setSpacing(0)
        self.gridLayout_15.setObjectName("gridLayout_15")
        spacerItem32 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem32, 0, 5, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.widget_10)
        self.label_29.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("color: rgb(105, 0, 255);\n"
"background-color: transparent;")
        self.label_29.setObjectName("label_29")
        self.gridLayout_15.addWidget(self.label_29, 0, 2, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.widget_10)
        self.line_7.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line_7.setStyleSheet("background-color: rgb(66, 2, 157);")
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setLineWidth(1)
        self.line_7.setMidLineWidth(0)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setObjectName("line_7")
        self.gridLayout_15.addWidget(self.line_7, 1, 0, 1, 6)
        self.label_30 = QtWidgets.QLabel(self.widget_10)
        self.label_30.setMinimumSize(QtCore.QSize(0, 20))
        self.label_30.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("background-color: transparent;")
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.gridLayout_15.addWidget(self.label_30, 0, 4, 1, 1)
        spacerItem33 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem33, 0, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.widget_10)
        self.label_32.setStyleSheet("background-color: transparent;")
        self.label_32.setObjectName("label_32")
        self.gridLayout_15.addWidget(self.label_32, 2, 1, 1, 4)
        self.label_31 = QtWidgets.QLabel(self.widget_10)
        self.label_31.setMinimumSize(QtCore.QSize(0, 20))
        self.label_31.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("background-color: transparent;")
        self.label_31.setObjectName("label_31")
        self.gridLayout_15.addWidget(self.label_31, 0, 1, 1, 1)
        self.gridLayout_11.addWidget(self.widget_10, 0, 2, 1, 1)
        self.widget_11 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_11.setMinimumSize(QtCore.QSize(250, 120))
        self.widget_11.setMaximumSize(QtCore.QSize(250, 120))
        self.widget_11.setStyleSheet("background-color: rgba(255,255,255,.70);\n"
"color: rgb(66, 2, 157);\n"
"border-radius: 20px;")
        self.widget_11.setObjectName("widget_11")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.widget_11)
        self.gridLayout_16.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_16.setSpacing(0)
        self.gridLayout_16.setObjectName("gridLayout_16")
        spacerItem34 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem34, 0, 5, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.widget_11)
        self.label_33.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("color: rgb(105, 0, 255);\n"
"background-color: transparent;")
        self.label_33.setObjectName("label_33")
        self.gridLayout_16.addWidget(self.label_33, 0, 2, 1, 1)
        self.line_8 = QtWidgets.QFrame(self.widget_11)
        self.line_8.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line_8.setStyleSheet("background-color: rgb(66, 2, 157);")
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setLineWidth(1)
        self.line_8.setMidLineWidth(0)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setObjectName("line_8")
        self.gridLayout_16.addWidget(self.line_8, 1, 0, 1, 6)
        self.label_34 = QtWidgets.QLabel(self.widget_11)
        self.label_34.setMinimumSize(QtCore.QSize(0, 20))
        self.label_34.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("background-color: transparent;")
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.gridLayout_16.addWidget(self.label_34, 0, 4, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.widget_11)
        self.label_35.setMinimumSize(QtCore.QSize(0, 20))
        self.label_35.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("background-color: transparent;")
        self.label_35.setObjectName("label_35")
        self.gridLayout_16.addWidget(self.label_35, 0, 1, 1, 1)
        spacerItem35 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem35, 0, 0, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.widget_11)
        self.label_36.setStyleSheet("background-color: transparent;")
        self.label_36.setObjectName("label_36")
        self.gridLayout_16.addWidget(self.label_36, 2, 1, 1, 4)
        self.gridLayout_11.addWidget(self.widget_11, 1, 2, 1, 1)
        self.widget_12 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_12.setMinimumSize(QtCore.QSize(250, 120))
        self.widget_12.setMaximumSize(QtCore.QSize(250, 120))
        self.widget_12.setStyleSheet("background-color: rgba(255,255,255,.70);\n"
"color: rgb(66, 2, 157);\n"
"border-radius: 20px;")
        self.widget_12.setObjectName("widget_12")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.widget_12)
        self.gridLayout_17.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_17.setSpacing(0)
        self.gridLayout_17.setObjectName("gridLayout_17")
        spacerItem36 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem36, 0, 5, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.widget_12)
        self.label_37.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setStyleSheet("color: rgb(105, 0, 255);\n"
"background-color: transparent;")
        self.label_37.setObjectName("label_37")
        self.gridLayout_17.addWidget(self.label_37, 0, 2, 1, 1)
        self.line_9 = QtWidgets.QFrame(self.widget_12)
        self.line_9.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line_9.setStyleSheet("background-color: rgb(66, 2, 157);")
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setLineWidth(1)
        self.line_9.setMidLineWidth(0)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setObjectName("line_9")
        self.gridLayout_17.addWidget(self.line_9, 1, 0, 1, 6)
        self.label_38 = QtWidgets.QLabel(self.widget_12)
        self.label_38.setMinimumSize(QtCore.QSize(0, 20))
        self.label_38.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setStyleSheet("background-color: transparent;")
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.gridLayout_17.addWidget(self.label_38, 0, 4, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.widget_12)
        self.label_39.setMinimumSize(QtCore.QSize(0, 20))
        self.label_39.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setStyleSheet("background-color: transparent;")
        self.label_39.setObjectName("label_39")
        self.gridLayout_17.addWidget(self.label_39, 0, 1, 1, 1)
        spacerItem37 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem37, 0, 0, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.widget_12)
        self.label_40.setStyleSheet("background-color: transparent;")
        self.label_40.setObjectName("label_40")
        self.gridLayout_17.addWidget(self.label_40, 2, 1, 1, 4)
        self.gridLayout_11.addWidget(self.widget_12, 2, 2, 1, 1)
        self.button_add_note = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.button_add_note.setMinimumSize(QtCore.QSize(250, 120))
        self.button_add_note.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_add_note.setStyleSheet("background-color: rgba(255,255,255,.70);\n"
"color: rgb(66, 2, 157);\n"
"border-radius: 20px;")
        self.button_add_note.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/icon/new_notes.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_add_note.setIcon(icon9)
        self.button_add_note.setIconSize(QtCore.QSize(70, 70))
        self.button_add_note.setObjectName("button_add_note")
        self.gridLayout_11.addWidget(self.button_add_note, 0, 1, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_14.addWidget(self.scrollArea_2, 1, 1, 1, 1)
        spacerItem38 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem38, 1, 2, 1, 1)
        spacerItem39 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_14.addItem(spacerItem39, 2, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setStyleSheet("QPushButton:hover {\n"
"    border: 2px solid rgb(105, 0, 255);\n"
"}\n"
"\n"
"QPushButton #button_theme_1:hover {\n"
"    border: 6px solid #D2FA00;\n"
"}\n"
"\n"
"")
        self.page_4.setObjectName("page_4")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout_19.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_19.setSpacing(0)
        self.gridLayout_19.setObjectName("gridLayout_19")
        spacerItem40 = QtWidgets.QSpacerItem(56, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem40, 2, 4, 1, 1)
        spacerItem41 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_19.addItem(spacerItem41, 0, 1, 1, 1)
        spacerItem42 = QtWidgets.QSpacerItem(328, 208, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_19.addItem(spacerItem42, 2, 1, 1, 1)
        spacerItem43 = QtWidgets.QSpacerItem(56, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem43, 1, 2, 1, 1)
        spacerItem44 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_19.addItem(spacerItem44, 3, 3, 1, 1)
        self.widget_9 = QtWidgets.QWidget(self.page_4)
        self.widget_9.setMinimumSize(QtCore.QSize(225, 310))
        self.widget_9.setMaximumSize(QtCore.QSize(255, 310))
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_26 = QtWidgets.QLabel(self.widget_9)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_26.setObjectName("label_26")
        self.verticalLayout_2.addWidget(self.label_26)
        self.button_theme_1 = QtWidgets.QPushButton(self.widget_9)
        self.button_theme_1.setMinimumSize(QtCore.QSize(205, 85))
        self.button_theme_1.setStyleSheet("")
        self.button_theme_1.setText("")
        self.button_theme_1.setObjectName("button_theme_1")
        self.verticalLayout_2.addWidget(self.button_theme_1)
        self.button_theme_2 = QtWidgets.QPushButton(self.widget_9)
        self.button_theme_2.setMinimumSize(QtCore.QSize(205, 85))
        self.button_theme_2.setStyleSheet("")
        self.button_theme_2.setText("")
        self.button_theme_2.setObjectName("button_theme_2")
        self.verticalLayout_2.addWidget(self.button_theme_2)
        self.button_theme_3 = QtWidgets.QPushButton(self.widget_9)
        self.button_theme_3.setMinimumSize(QtCore.QSize(205, 85))
        self.button_theme_3.setSizeIncrement(QtCore.QSize(205, 85))
        self.button_theme_3.setStyleSheet("")
        self.button_theme_3.setText("")
        self.button_theme_3.setObjectName("button_theme_3")
        self.verticalLayout_2.addWidget(self.button_theme_3)
        self.gridLayout_19.addWidget(self.widget_9, 0, 3, 3, 1)
        self.widget_13 = QtWidgets.QWidget(self.page_4)
        self.widget_13.setObjectName("widget_13")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.widget_13)
        self.gridLayout_18.setContentsMargins(10, 0, 6, 0)
        self.gridLayout_18.setHorizontalSpacing(10)
        self.gridLayout_18.setVerticalSpacing(30)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.label_41 = QtWidgets.QLabel(self.widget_13)
        self.label_41.setMinimumSize(QtCore.QSize(95, 30))
        self.label_41.setMaximumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_41.setObjectName("label_41")
        self.gridLayout_18.addWidget(self.label_41, 1, 0, 1, 2)
        self.comboBox = QtWidgets.QComboBox(self.widget_13)
        self.comboBox.setMinimumSize(QtCore.QSize(120, 25))
        self.comboBox.setMaximumSize(QtCore.QSize(120, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox.setFont(font)
        self.comboBox.setWhatsThis("")
        self.comboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox.setAutoFillBackground(False)
        self.comboBox.setStyleSheet("color: rgb(66, 2, 157);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_18.addWidget(self.comboBox, 0, 2, 1, 1)
        self.button_update = QtWidgets.QPushButton(self.widget_13)
        self.button_update.setMinimumSize(QtCore.QSize(120, 25))
        self.button_update.setMaximumSize(QtCore.QSize(120, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.button_update.setFont(font)
        self.button_update.setStyleSheet("")
        self.button_update.setObjectName("button_update")
        self.gridLayout_18.addWidget(self.button_update, 1, 2, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.widget_13)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_27.setObjectName("label_27")
        self.gridLayout_18.addWidget(self.label_27, 1, 3, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.widget_13)
        self.label_28.setMinimumSize(QtCore.QSize(95, 0))
        self.label_28.setMaximumSize(QtCore.QSize(95, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_28.setObjectName("label_28")
        self.gridLayout_18.addWidget(self.label_28, 2, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.widget_13)
        self.label_25.setMinimumSize(QtCore.QSize(95, 30))
        self.label_25.setMaximumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_25.setObjectName("label_25")
        self.gridLayout_18.addWidget(self.label_25, 0, 0, 1, 1)
        self.button_notifications = QtWidgets.QPushButton(self.widget_13)
        self.button_notifications.setMinimumSize(QtCore.QSize(120, 25))
        self.button_notifications.setMaximumSize(QtCore.QSize(120, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.button_notifications.setFont(font)
        self.button_notifications.setStyleSheet("")
        self.button_notifications.setObjectName("button_notifications")
        self.gridLayout_18.addWidget(self.button_notifications, 2, 2, 1, 1)
        self.gridLayout_19.addWidget(self.widget_13, 1, 1, 1, 1)
        spacerItem45 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem45, 2, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_4)
        self.gridLayout_4.addWidget(self.stackedWidget, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.widget_3, 0, 2, 1, 1)
        MainPageWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainPageWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.buttonHome.toggled['bool'].connect(self.buttonHome.setChecked) # type: ignore
        self.buttonCalendar.toggled['bool'].connect(self.buttonCalendar.setChecked) # type: ignore
        self.buttonNotes.toggled['bool'].connect(self.buttonNotes.setChecked) # type: ignore
        self.buttonSettings.toggled['bool'].connect(self.buttonSettings.setChecked) # type: ignore
        self.buttonSettings.toggled['bool'].connect(self.button_left_Settings.setChecked) # type: ignore
        self.buttonNotes.toggled['bool'].connect(self.button_left_Notes.setChecked) # type: ignore
        self.buttonCalendar.toggled['bool'].connect(self.button_leftCalendar.setChecked) # type: ignore
        self.buttonHome.toggled['bool'].connect(self.button_left_Home.setChecked) # type: ignore
        self.buttonBack.pressed.connect(self.main_Menu.close) # type: ignore
        self.buttonBack.pressed.connect(self.left_menu.show) # type: ignore
        self.buttonMenu.pressed.connect(self.main_Menu.show) # type: ignore
        self.buttonMenu.pressed.connect(self.left_menu.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainPageWindow)

    def retranslateUi(self, MainPageWindow):
        _translate = QtCore.QCoreApplication.translate
        MainPageWindow.setWindowTitle(_translate("MainPageWindow", "MainWindow"))
        self.buttonCalendar.setText(_translate("MainPageWindow", "Calendar"))
        self.buttonHome.setText(_translate("MainPageWindow", "Home"))
        self.buttonSettings.setText(_translate("MainPageWindow", "Settings"))
        self.buttonNotes.setText(_translate("MainPageWindow", "Notes"))
        self.label.setText(_translate("MainPageWindow", "20:20"))
        self.label_2.setText(_translate("MainPageWindow", "Jun 21"))
        self.label_16.setText(_translate("MainPageWindow", "Progress 0%"))
        self.label_6.setText(_translate("MainPageWindow", "Добавить описание страниц на сайте\n"
"Удалить баги"))
        self.label_4.setText(_translate("MainPageWindow", "Work"))
        self.label_3.setText(_translate("MainPageWindow", "Theme:"))
        self.label_5.setText(_translate("MainPageWindow", "20:20 jun 21"))
        self.checkBox_3.setText(_translate("MainPageWindow", "Done"))
        self.checkBox_2.setText(_translate("MainPageWindow", "Done"))
        self.label_9.setText(_translate("MainPageWindow", "Theme:"))
        self.label_7.setText(_translate("MainPageWindow", "Добавить описание страниц на сайте\n"
"Удалить баги"))
        self.label_8.setText(_translate("MainPageWindow", "Work"))
        self.label_10.setText(_translate("MainPageWindow", "20:20 jun 21"))
        self.label_11.setText(_translate("MainPageWindow", "Добавить описание страниц на сайте\n"
"Удалить баги"))
        self.label_12.setText(_translate("MainPageWindow", "Work"))
        self.label_13.setText(_translate("MainPageWindow", "Theme:"))
        self.label_14.setText(_translate("MainPageWindow", "20:20 jun 21"))
        self.checkBox.setText(_translate("MainPageWindow", "Done"))
        self.label_21.setText(_translate("MainPageWindow", "20:20 jun 21"))
        self.label_22.setText(_translate("MainPageWindow", "Добавить описание страниц на сайте\n"
"Удалить баги"))
        self.label_23.setText(_translate("MainPageWindow", "Work"))
        self.label_24.setText(_translate("MainPageWindow", "Theme:"))
        self.label_17.setText(_translate("MainPageWindow", "Work"))
        self.label_18.setText(_translate("MainPageWindow", "Theme:"))
        self.label_19.setText(_translate("MainPageWindow", "20:20 jun 21"))
        self.label_20.setText(_translate("MainPageWindow", "Добавить описание страниц на сайте\n"
"Удалить баги"))
        self.label_29.setText(_translate("MainPageWindow", "Work"))
        self.label_30.setText(_translate("MainPageWindow", "20:20 jun 21"))
        self.label_32.setText(_translate("MainPageWindow", "Добавить описание страниц на сайте\n"
"Удалить баги"))
        self.label_31.setText(_translate("MainPageWindow", "Theme:"))
        self.label_33.setText(_translate("MainPageWindow", "Work"))
        self.label_34.setText(_translate("MainPageWindow", "20:20 jun 21"))
        self.label_35.setText(_translate("MainPageWindow", "Theme:"))
        self.label_36.setText(_translate("MainPageWindow", "Добавить описание страниц на сайте\n"
"Удалить баги"))
        self.label_37.setText(_translate("MainPageWindow", "Work"))
        self.label_38.setText(_translate("MainPageWindow", "20:20 jun 21"))
        self.label_39.setText(_translate("MainPageWindow", "Theme:"))
        self.label_40.setText(_translate("MainPageWindow", "Добавить описание страниц на сайте\n"
"Удалить баги"))
        self.label_26.setText(_translate("MainPageWindow", "Theme:"))
        self.label_41.setText(_translate("MainPageWindow", "Check update:"))
        self.comboBox.setItemText(0, _translate("MainPageWindow", "English"))
        self.comboBox.setItemText(1, _translate("MainPageWindow", "Russian"))
        self.button_update.setText(_translate("MainPageWindow", "Update"))
        self.label_27.setText(_translate("MainPageWindow", "You don\'t have \n"
"any updates"))
        self.label_28.setText(_translate("MainPageWindow", "Notifications in \n"
"Telegram:"))
        self.label_25.setText(_translate("MainPageWindow", "Language: "))
        self.button_notifications.setText(_translate("MainPageWindow", "Disable"))
import static.resources_rc
